### ISSUE TITLE
Normalized WH Prediction seems to get better performance

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/pytorch-yolo-v2-v3#27]
https://github.com/developer0hye/YOLOv3-PyTorch-Colab

https://colab.research.google.com/drive/1ikcj4kJ2N1ny3jIHuEFIZTnwlV9-nCw4

I am experimenting with the variant of your code.

I got the higher mAP with normalized wh prediction instead of wh divided by the stride.

The results of 170 epoch trained yolv3 tiny

AP for aeroplane = 0.7843
AP for bicycle = 0.8139
AP for bird = 0.6702
AP for boat = 0.6116
AP for bottle = 0.5703
AP for bus = 0.8028
AP for car = 0.8394
AP for cat = 0.8012
AP for chair = 0.5465
AP for cow = 0.7497
AP for diningtable = 0.6677
AP for dog = 0.7366
AP for horse = 0.8391
AP for motorbike = 0.8023
AP for person = 0.7880
AP for pottedplant = 0.4613
AP for sheep = 0.7257
AP for sofa = 0.6991
AP for train = 0.8025
AP for tvmonitor = 0.7194
**Mean AP = 0.7216**

**Comment by yjh0410** [comment]
You means that you didn't divide all acnhor boxes with stride, right?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 中午11:27
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
https://github.com/developer0hye/YOLOv3-PyTorch-Colab
 
https://colab.research.google.com/drive/1ikcj4kJ2N1ny3jIHuEFIZTnwlV9-nCw4
 
I am experimenting with the variant of your code.
 
I got the higher mAP with normalized wh prediction instead of wh divided by the stride.
 
The results of 170 epoch trained yolv3 tiny
 
AP for aeroplane = 0.7843
 AP for bicycle = 0.8139
 AP for bird = 0.6702
 AP for boat = 0.6116
 AP for bottle = 0.5703
 AP for bus = 0.8028
 AP for car = 0.8394
 AP for cat = 0.8012
 AP for chair = 0.5465
 AP for cow = 0.7497
 AP for diningtable = 0.6677
 AP for dog = 0.7366
 AP for horse = 0.8391
 AP for motorbike = 0.8023
 AP for person = 0.7880
 AP for pottedplant = 0.4613
 AP for sheep = 0.7257
 AP for sofa = 0.6991
 AP for train = 0.8025
 AP for tvmonitor = 0.7194
 Mean AP = 0.7216

**Comment by developer0hye** [comment]
Yeah, I divide all anchor boxes with input size.
I make the model to predict normalized width and height(0~1)
So, I divide your default anchor with 13 and then got the normalized anchor box.

**Comment by yjh0410** [comment]
Oh! Sounds good!


See the formulation:
tw = log(box_w/p_w)


I think we needn't to divide them by width of input image beacuse of:
tw = log((box_w*w)/(p_w*w))=log(box_w/p_w)


I will try this on YOLO-v3. Maybe there is also some improvement!


In addition, I replace the SubtractMean func with Normalize func in data_augment following your advice.


class&nbsp;Normalize(object):
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;mean,&nbsp;std):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.mean&nbsp;=&nbsp;np.array(mean,&nbsp;dtype=np.float32)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.std&nbsp;=&nbsp;np.array(mean,&nbsp;dtype=np.float32)

&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__call__(self,&nbsp;image,&nbsp;boxes=None,&nbsp;labels=None):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image&nbsp;=&nbsp;image.astype(np.float32)&nbsp;/&nbsp;255.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image&nbsp;-=&nbsp;self.mean
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image&nbsp;/=&nbsp;self.std
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;image.astype(np.float32),&nbsp;boxes,&nbsp;labels





where the mean=(0.485, 0.456, 0.406) and std=(0.229, 0.224, 0.225) which are used in imagenet.


I wish it will bring some improvement.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 中午11:31
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
Yeah, I divide all anchor boxes with input size.
 I make the model predict normalized width and height(0~1)
 So, I divide your default anchor with 13 and then got the normalized anchor box.

**Comment by developer0hye** [comment]
I hope too!

Also, be careful about calculating the bounding box!

https://github.com/developer0hye/YOLOv3-PyTorch-Colab/blob/92b191d64c4e730607318cbd9514e41794fbf743/model.py#L211-L222

**Comment by yjh0410** [comment]
Hellow!
I finished training my yolo-v2 with normalize data_augment. But I get a little worse result:
Previous：74.4%（416）and 76.8%（608）
Now：74.3%（416） and 76.0%（608）


I'm not sure this is because of something random or the normalize data_augment.


Nevertheless, I want to keep the normalize data_augment.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 中午11:46
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
I hope too!
 
Also, be careful about calculating the bounding box!
 
https://github.com/developer0hye/YOLOv3-PyTorch-Colab/blob/92b191d64c4e730607318cbd9514e41794fbf743/model.py#L211-L222

**Comment by developer0hye** [comment]
@yjh0410 
Good Experiment!

Do you modify the base transform used in voc_eval.py?

**Comment by yjh0410** [comment]
Yes, I do.
&nbsp;&nbsp;&nbsp;&nbsp;dataset&nbsp;=&nbsp;VOCDetection(args.voc_root,&nbsp;[('2007',&nbsp;set_type)],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BaseTransform(net.input_size,&nbsp;mean=(0.485,&nbsp;0.456,&nbsp;0.406),&nbsp;std=(0.229,&nbsp;0.224,&nbsp;0.225)),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VOCAnnotationTransform())





I tend to think that this is because of something random like random sample，random initialization.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 下午4:52
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
@yjh0410
 Good Experiment!
 
Do you modify the base transform used in voc_eval.py?

**Comment by developer0hye** [comment]
I think so! Did you train the model with normalized wh prediction??

**Comment by yjh0410** [comment]
I'm training the tiny-yolo-v3 with normalized wh prediction and normalize data_augment. Looking forward to good news ！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 下午5:17
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
I think so! Did you train the model with normalized wh prediction??

**Comment by developer0hye** [comment]
@yjh0410 
Ah Okay!!! You make me inspired!
Are you a student or researcher??

**Comment by yjh0410** [comment]
Haha！I’m a student.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 下午5:42
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
@yjh0410
 Ah Okay!!! You make me inspired!
 Are you a student or researcher??

**Comment by developer0hye** [comment]
Ah, me too. Actually I am a graduate student. KK I was curious about this.

**Comment by yjh0410** [comment]
Fighting！Fighting！！
You also make me inspired. I believe you will do a very great job！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 下午5:51
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
Ah, me too. Actually I am a graduate student. KK I was curious about this.

**Comment by developer0hye** [comment]
@yjh0410 
Thanks! Fighting！Fighting!!! I also believe in you!!~

**Comment by yjh0410** [comment]
This is my tiny-yolo-v3's mAP:


AP for aeroplane = 0.7967
AP for bicycle = 0.8083
AP for bird = 0.6907
AP for boat = 0.5946
AP for bottle = 0.5727
AP for bus = 0.8075
AP for car = 0.8332
AP for cat = 0.8078
AP for chair = 0.5523
AP for cow = 0.7414
AP for diningtable = 0.6883
AP for dog = 0.7560
AP for horse = 0.7956
AP for motorbike = 0.8130
AP for person = 0.7872
AP for pottedplant = 0.4576
AP for sheep = 0.7254
AP for sofa = 0.7081
AP for train = 0.7894
AP for tvmonitor = 0.6993
Mean AP = 0.7213
~~~~~~~~



I use the normalize data_augment and no any division on anchor boxes or groundtruth boxes. It is better than original result 71.3% mAP.


Although with division and without divison are mathematically equivalent, I think there is something about trade-off for a computer bringing the above different result.


Following that, I'm training yolo-v3 which consumes about 24 hours. And I plan to update all my models with normalize data_augment（Even though it doesn't bring any improvement，almost detectors use that. I think there is something I haven't known, and I need to study it deeply and check my data_augment codes carefully.）.


Looking forward to good news！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 晚上8:57
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
@yjh0410
 Thanks! Fighting！Fighting!!! I also believe in you!!~
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by developer0hye** [comment]
Yeah!! Great! Keep up the good work!

**Comment by developer0hye** [comment]
So, the range of predicted wh of your model is 0 to 1? or 0 to img.width and 0 to img.height??

**Comment by yjh0410** [comment]
Yolo-v3 predicts the tw and th which are equal to log(box_w / pw) and log(box_h / p_h) instead of wh. They are both small increments.&nbsp;


My all anchor boxes are as following:(Original anchor boxes \times 32)
MULTI_ANCHOR_SIZE&nbsp;=&nbsp;[[32.64,&nbsp;47.68],&nbsp;[50.24,&nbsp;108.16],&nbsp;[126.72,&nbsp;96.32],&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[78.4,&nbsp;201.92],&nbsp;[178.24,&nbsp;178.56],&nbsp;[129.6,&nbsp;294.72],&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[331.84,&nbsp;194.56],&nbsp;[227.84,&nbsp;325.76],&nbsp;[365.44,&nbsp;358.72]]&nbsp;&nbsp;&nbsp;


#&nbsp;MULTI_ANCHOR_SIZE&nbsp;=&nbsp;[[1.02,&nbsp;1.49],&nbsp;[1.57,&nbsp;3.38],&nbsp;[3.96,&nbsp;3.01],&nbsp;&nbsp;&nbsp;&nbsp;
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2.45,&nbsp;6.31],&nbsp;[5.57,&nbsp;5.58],&nbsp;[4.05,&nbsp;9.21],&nbsp;&nbsp;&nbsp;&nbsp;
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[10.37,&nbsp;6.08],&nbsp;[7.12,&nbsp;10.18],&nbsp;[11.42,&nbsp;11.21]]&nbsp;&nbsp;&nbsp;








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 中午11:08
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
So, the range of predicted wh of your model is 0 to 1? or 0 to img.width and 0 to img.height??

**Comment by developer0hye** [comment]
What happed when we train the model with mutl scale??

Is the anchor size changed??

**Comment by yjh0410** [comment]
During multi scale training stage, We change nothing but only input size. It works for my yolov2, but dose not for my yolov3. I'm not sure why.&nbsp;



---Original---

**Comment by developer0hye** [comment]
I think... to solve the problem we should use the normalized anchor box[0, 1] for supporting invariant to input shape.

**Comment by yjh0410** [comment]
Maybe. I will try again following your advice.



---Original---

**Comment by developer0hye** [comment]
@yjh0410 
Thanks! I am also trying the various methods to improve performance!

**Comment by yjh0410** [comment]
Hellow!


I have tried some menthos to improve my model. But almost failed. For example：


Method 1: Normalize ab to [0, 1], also gt box.
In tiny-yolo-v2.py, I divided anchor boxes by 13 to normalize them to [0, 1], and also normalize gt box with input size to [0, 1]. But this maked my tiny v2 drop some points——60.2% vs 61.6%. Tiny-v3 didn't, either.


Method 2: *Use the original anchor boxes, no division, and success !
After I multiplied my all anchor boxes by 32 to map them into the scale of input size(416) (and normalize data_augment), yolo-v3 got 81.0 mAP higher than my previous result 80.8 mAP. Thanks a lot for your advice !!



Method 3: Use xywh to compute loss instead of txtytwth which I used to compute loss
I find some YOLO-v3 projects predicts txtytwth and maps them to xywh, then adds xywh into loss function while I use txtytwth to compute loss. So I tried the former one, but got a worse result: 68 % vs 72.1%(tiny v3). Tiny-v2 dropped much, too. Perhaps there are some hidden tricks I don't know. But I'm sure that YOLOv3 uses tw, th according to his paper.


I'm struggling with multi-scale training trick for my v3.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 中午1:47
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
@yjh0410
 Thanks! I am also trying the various methods to improve performance!

**Comment by developer0hye** [comment]
@yjh0410 
Thanks a lot for your exeperiments! 

I also have tried some methods.

Method 1: Use Sigmoid instead of Softmax to predict the class
I got a worse result. But, the official implementation used sigmoid to predict the class of objects. So, I keep up the sigmoid implementation!

yolov3 tiny with softmax: 72.5 %
yolov3 tiny with sigmoid: 72.1 %

Keep up the good work!! Fighting! Fighting!!

**Comment by developer0hye** [comment]
@yjh0410 
Ah, I also have a plan that is applying other learning rate decay methods like cosine decay scheduler.

**Comment by yjh0410** [comment]
Sounds reasonable !
I have never tried other lr schedulers.
I also plan to use focal loss to compute class loss with sigmoid not softmax.
Looking forward to your good news !!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 中午11:25
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Normalized WH Prediction seems to get better performance (#27)





 
@yjh0410
 Ah, I also have a plan that is applying other learning rate decay methods like cosine decay scheduler.

**Comment by developer0hye** [comment]
@yjh0410 
And I have a plan to support to resume of the training!
